In [1]:
import numpy as np
py_list = [1,2,3,4,5]
np_array = np.array([1,2,3,4,5])
print(type(py_list))
print(type(np_array))

<class 'list'>
<class 'numpy.ndarray'>


In [2]:
import time
size = 1_000_000

a = list(range(size))
b = list(range(size))
start = time.time()
c = [a[i] + b[i] for i in range(size)]
print(f"Python list time: {time.time() - start:.4f} seconds")

# NumPy
a_np = np.arange(size)
b_np = np.arange(size)

start = time.time()
c_np = a_np + b_np
print(f"NumPy time: {time.time() - start:.4f} seconds")

Python list time: 0.1146 seconds
NumPy time: 0.0035 seconds


In [3]:
# 1D array — like a single row of data
a = np.array([1, 2, 3, 4, 5])
print("1D:", a.shape)  # (5,) — 5 elements

# 2D array — like a table (rows x columns)
b = np.array([[1, 2, 3],
              [4, 5, 6]])
print("2D:", b.shape)  # (2, 3) — 2 rows, 3 columns

# 3D array — like a batch of images (batch x height x width)
c = np.zeros((3, 28, 28))  # 3 images, 28x28 pixels each
print("3D:", c.shape)

1D: (5,)
2D: (2, 3)
3D: (3, 28, 28)


In [4]:
a = np.array([1, 2, 3, 4, 5], dtype=np.float32)

# Basic operations — applied to every element
print(a * 2)
print(a ** 2)
print(np.sqrt(a))

# Aggregate operations
print("Mean:", a.mean())
print("Sum:", a.sum())
print("Max:", a.max())
print("Min:", a.min())
print("Std:", a.std())

# 2D operations
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Column means:", matrix.mean(axis=0))  # mean of each column
print("Row means:", matrix.mean(axis=1))     # mean of each row

[ 2.  4.  6.  8. 10.]
[ 1.  4.  9. 16. 25.]
[1.        1.4142135 1.7320508 2.        2.236068 ]
Mean: 3.0
Sum: 15.0
Max: 5.0
Min: 1.0
Std: 1.4142135
Column means: [4. 5. 6.]
Row means: [2. 5. 8.]


In [5]:
a = np.array([10, 20, 30, 40, 50])

print(a[0])      # first element
print(a[-1])     # last element
print(a[1:4])    # elements at index 1, 2, 3
print(a[::2])    # every other element

# 2D indexing
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print(matrix[0])        # first row
print(matrix[:, 1])     # second column — this one is important
print(matrix[1:, 1:])   # bottom right 2x2 submatrix

10
50
[20 30 40]
[10 30 50]
[1 2 3]
[2 5 8]
[[5 6]
 [8 9]]


In [6]:
a = np.arange(12)  # [0, 1, 2, ..., 11]
print(a.shape)

# Reshape into 3 rows, 4 columns
b = a.reshape(3, 4)
print(b)
print(b.shape)

# Reshape into 2 groups of 2 rows of 3 columns
c = a.reshape(2, 2, 3)
print(c.shape)

# Flatten back to 1D
print(c.flatten().shape)

(12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
(2, 2, 3)
(12,)


In [8]:
#Numpy Exercise
import numpy as np
arr = np.random.randint(0, 100, size=(4, 5))
print("Array:\n", arr)
print("\nShape:", arr.shape)
print("Mean:", arr.mean())
print("Max:", arr.max())
print("Min:", arr.min())

print("\nSecond column:")
print(arr[:, 1])

print("\nLast two rows:")
print(arr[-2:, :])

reshaped = arr.reshape(2, 10)
print("\nReshaped (2,10):\n", reshaped)

min_val = arr.min()
max_val = arr.max()
normalized = (arr - min_val) / (max_val - min_val)

print("\nNormalized array:\n", normalized)

Array:
 [[27 94 48 28 90]
 [44 35 49 61 92]
 [34 84 96 75 41]
 [69 72 99 53 31]]

Shape: (4, 5)
Mean: 61.1
Max: 99
Min: 27

Second column:
[94 35 84 72]

Last two rows:
[[34 84 96 75 41]
 [69 72 99 53 31]]

Reshaped (2,10):
 [[27 94 48 28 90 44 35 49 61 92]
 [34 84 96 75 41 69 72 99 53 31]]

Normalized array:
 [[0.         0.93055556 0.29166667 0.01388889 0.875     ]
 [0.23611111 0.11111111 0.30555556 0.47222222 0.90277778]
 [0.09722222 0.79166667 0.95833333 0.66666667 0.19444444]
 [0.58333333 0.625      1.         0.36111111 0.05555556]]
